#!/usr/bin/env python

import csv
import os
import sys

import matplotlib.pyplot as plt
import numpy as np

import common


def main():
    dsp = sys.argv[1]
    directory, filename = os.path.split(dsp)
    basename, _ = os.path.splitext(filename)
    output = f'{directory}/{basename}-width.png'
    strategies = list(range(5))
    metrics_files = [f'{directory}/{basename}.fcsched/{basename}_ss{s}_metrics.csv' for s in strategies]

    plt.rcParams['figure.dpi'] = 512

    fix, ax = plt.subplots()
    for strategy, path in enumerate(metrics_files):
        metrics = read_width(path)
        ax.plot(metrics, label=common.strategy_labels[str(strategy)])

    ax.legend()
    plt.savefig(output, bbox_inches="tight")


def read_width(path):
    with open(path) as csvfile:
        reader = csv.reader(csvfile, delimiter=';')
        row = next(r for r in reader if r[0] == 'width')
        return np.array(list(map(int, row[1:])))


if __name__ == "__main__":
    main()
