#!/bin/bash

CXX=${CXX:-clang++}
faust=/home/simon/dev/faust/build/bin/faust
share=/home/simon/dev/faustschedulerbenchtool/fctool

# check if the user has provided the right number of arguments
if [ $# -lt 1 ] || [ $# -gt 3 ]; then
    echo "Usage: $0 <dspfile> <ss> <output>"
    exit 1
fi

dsp=$1
name=${dsp%.dsp}
ss=${2:-0}
output=$3

$faust -lang ocpp -ss $ss $dsp \
    | cat $share/bencharch_header.cpp - $share/bencharch_footer.cpp \
    | $CXX -O3 -ffast-math -march=native -x c++ - -o $output
